spring.application.name=backendSpring

# 서버 포트 (Node.js와 동일하게 맞추거나 중복 피하기)
server.port=5000

# MongoDB 연결 정보 (도커 DB 이름이 ShopDB인 경우)
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/ShopDB}

jwt.secret=${JWT_SECRET:v9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B?E(G+KbPeShVmYq}
jwt.expiration=3600000